name = "QXGraph"
uuid = "b15f1ded-d19a-4aca-a940-1991fcfc7750"
authors = ["QuantEx team"]
version = "0.1.2"

[deps]
LightGraphs = "093fc24a-ae57-5d10-9952-331d41423f4d"

[compat]
julia = "1.5"
LightGraphs = "1.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
